export const tooltipContent = {
  pid: `StakePool's ID`,
  state: `- Ready: Not mining
- Mining: Mining normally
- Unresponsive: The miner is disconnected; could be slashed
- CoolingDown：The stake is locked. No reward is generated. After 7 days the owner can reclaim the worker and get back the stake.`,
  mined: 'The total reward generated by this worker',
}
